import java.time.LocalDateTime;

public class Event
{
    int id;
    String eName;
    EventType eType;
    LocalDateTime startDateTime;
    LocalDateTime endDateTime;
    User createdBy;
    LocalDateTime createdTime;
    static int autoGeneratedId;
    public Event(String eName,EventType eType,LocalDateTime startDateTime,LocalDateTime endDateTime,User createdBy,LocalDateTime createdTime) {
    	this.id = autoGeneratedId++;
    	this.eName = eName;
    	this.eType = eType;
    	this.startDateTime = startDateTime;
    	this.endDateTime = endDateTime;
    	this.createdBy = createdBy;
    	this.createdTime = createdTime;
    	
    	
	}
    public void print()
    {
    	System.out.println("Event Id = " + id );
    	System.out.println("Event Name = " + eName); 
    	System.out.println("Event startDateTime = " + startDateTime);
    	System.out.println("Event endDateTime = " + endDateTime);
    	System.out.println("Event CreatedTime " + createdTime);
    }
    
    public boolean checkConflict(Event event)
	{
    	if(event.startDateTime.isEqual(startDateTime) || event.startDateTime.isEqual(endDateTime) ||
    			event.endDateTime.isEqual(startDateTime) || event.endDateTime.isEqual(endDateTime)) {
    		return true;
    	}
		if(event.startDateTime.isAfter(startDateTime)  && event.startDateTime.isBefore(endDateTime)) {
			return true;
		}
			
		if(event.endDateTime.isAfter(startDateTime) && event.endDateTime.isBefore(endDateTime)) {
			return true;
		}
		
		return false;
	}
    
    public boolean equals(Event event) {
		if(event.id == id) {
			return true;
		}
		return false;
	}
}

   	
    	
    

