public class User
{
	int id;
	String  name;
	private Calendar calendar;
	private static int autoGeneratedID =1;
	
    public User(String name) 
    {
    	this.name = name;
    	this.id = autoGeneratedID++;
    	System.out.println("User created with Id = " + this.id);
    }
    
    public void setCalendar(Calendar calendar) 
    {
		this.calendar = calendar;
	}
    public void removeCalendar() 
    {
    	this.calendar = null;
    	System.out.println("Deleted Calendar Successfully");
    	
    }
}
